name: Update Docker Hub Description
on:
  push:
    branches:
      - main
    paths:
      - README.md
      - .github/workflows/document.yml
  workflow_dispatch:
jobs:
  description:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Docker Hub Description
      uses: peter-evans/dockerhub-description@v4
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        repository:  ${{ vars.DOCKERHUB_REPO }}
        readme-filepath: ./README.md
        short-description: ${{ github.event.repository.description }}
        enable-url-completion: true
